Create table practice(
    id SERIAL PRIMARY KEY, --FOR AUTO INCREMENT
    NAME VARCHAR(100) NOT NULL, -- VARCHAR FOR THE STRING AND NOT NULL SO THAT IT MUST BE FILLED
    AGE INT DEFAULT 18, --DEFAULT SET AGE 18
    PHONE_NO VARCHAR(11) UNIQUE CHECK(LENGTH(PHONE_NO)==11) --CANT BE DUPLICATE  CHECK ANY VALUE
);